version: "3.8"

services:
  app:
    build: .
    image: redasaad123/elhaq
    env_file:
      - .env
    ports:
      - "8080"    # داخلي داخل الشبكة، NGINX هيوجهه للـ app
    networks:
      - webnet
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - webnet
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - webnet
    command: certonly --webroot --webroot-path=/var/www/html --email support@elhaq.duckdns.org --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d elhaq.duckdns.org
    restart: "no"
  
  certbot-renew:
    image: certbot/certbot
    volumes:
      - webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do
        certbot renew --quiet && docker exec nginx nginx -s reload;
        sleep 12h & wait $${!};
      done;"
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:

volumes:
  webroot:
  certbot-etc:
  certbot-var:
